### ISSUE TITLE
suggests

### ISSUE THREAD

**Issue by unknowtech** [TheRedSpy15/LTECleanerFOSS#21]
a programmer for automatic cleaning

currently we can add exceptions to the white list but not delete them

how I can help to translate into french

improve the interface with design material

where can you make a donation ? i don,t have paypal 

thank you

**Comment by TheRedSpy15** [comment]
Hello! Sorry but your post is a little unclear

You actually can delete added exceptions to the whitelist, besides for the default ones (might add the ability to remove them too)

You can help translate to French using the app "stringlate" on F-droid (if you aren't familiar with translating android)

The interface is still a work in progress, espacially the settings menu

I don't accept donations, I do this purely because I love to code :)

**Comment by unknowtech** [comment]
thank , 

we can't delete whitelists by delfaut

an automatic cleaning mode would be nice
example every day at 14h00

**Comment by DuMuT6p** [comment]
@TheRedSpy15 I also couldn't figure out how to delete the whitelisted default entries. If it is already there can you please explain ? If not - this is just a reminder that it would be a nice feature. Also restoring the default whitelist changed by accident.

**Comment by TheRedSpy15** [comment]
@DuMuT6p Currently you cannot delete the default whitelists. This is a planned feature however
