### ISSUE TITLE
Fdroid build still requires internet permission

### ISSUE THREAD

**Issue by TheRedSpy15** [TheRedSpy15/LTECleanerFOSS#218]
> **There is a plus to this!** Fdroid & Github releases will be zero ads and zero networking permissions!

![Screenshot_2021-10-10-08-16-28](https://user-images.githubusercontent.com/48226312/136679563-4a75cbae-779b-4801-8af3-9b308bf0b077.jpeg)
Why "view network connections" permission?🤔

_Originally posted by @shuvashish76 in https://github.com/TheRedSpy15/LTECleanerFOSS/discussions/205#discussioncomment-1453959_

**Comment by TheRedSpy15** [comment]
@shuvashish76 have you tried reinstalling the app completely?

**Comment by shuvashish76** [comment]
Checked with both
GitHub version: `4.8.3 (47)`
F-Droid version: `4.8.1 (45)`

---
![Screenshot_2021-10-10-10-00-04](https://user-images.githubusercontent.com/48226312/136682179-6b6f4e61-5f64-4f39-929e-c8b0bf8b4840.jpeg)
(Manifest view from [AppManager](https://github.com/MuntashirAkon/AppManager))

**Comment by TheRedSpy15** [comment]
Its showing up in my virtual device actually.... I'll look into it further, but it might be because of workmanager, which is how it automatically schedules cleaning on the system. If that's the case, my code doesn't have the ability to access the internet since it isn't declaring that permission in it's own manifest. Workmanager is built into the OS, so it won't do anything that it shouldn't

However that might not be the case, since I don't use any constraints for workmanager regarding networking. But again, I'll keep investigating

**Comment by gallegonovato** [comment]
Good evening @TheRedSpy15 

Lte permissions downloaded from google play store are different from fdroid.

I comment because I asked a friend who uses google stuff. I use lineageos without gaps and everything from fdroid or github, gitlab or codeberg.

And he sent me these screenshots of the lte permissions downloaded from the Google Play Store:

https://ibb.co/s3R5Q3j
https://ibb.co/YL0mTcs
https://ibb.co/4g1X7Ck
https://ibb.co/R919Bkv
https://ibb.co/YQBSDSH

It is from the lte application on S9+ mobile.

So there are differences.

Haber if I can try on same phone of another friend, who also does not use anything from Google to corroborate it well.

Thanks for sharing.

**Comment by HonestAbe7** [comment]
Thanks. I just restricted the background data and will see if this works.
    On Thursday, October 14, 2021, 10:25:40 AM EDT, gallegonovato ***@***.***> wrote:  
 
 



Interesting. I saw this did use a very small amount of data in my data usage. I am hoping this can be fully used without any data in the future.


Good afternoon:

I tested and it does not consume data.

But in settings, applications, lte. Disable data in both foreground and background. Haber if so.

The only thing that lte now starts if or if with the system. Even if you have disabled the daily cleaning in the lte settings. Which should not start with the system, but it may also be because of the permission to see the networks.

You can prevent system boot but you have to be root and superuser.

Best regards

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TheRedSpy15** [comment]
Fixed 4f268f8eb34c98b351fa36958d2bde9ea9544020
