### ISSUE TITLE
Nav var cuts the clean button

### ISSUE THREAD

**Issue by sebadamus** [TheRedSpy15/LTECleanerFOSS#57]
Description:
---

Kind of the app don't mind the nav bar and it's behind it, Android 9 stock xiaomi a2 lite

Device info:
---
<table>
<tr><td>App version</td><td>4.0.6</td></tr>
<tr><td>App version code</td><td>32</td></tr>
<tr><td>Android build version</td><td>V10.0.13.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.13.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by TheRedSpy15** [comment]
I'm so sorry, I sorta don't understand what you mean

**Comment by puppykickr** [comment]
> I'm so sorry, I sorta don't understand what you mean

I know exactly what he means.
I was going to post an issue, but I found this.

I believe I am correct when I say rhat I have the same problem on my Poblano VLE5 running 8.1.0

The navigation bar completely covers the 'clean' button, rendering the app unable to be used.

Also, the entire wording on the screen is not centered, allowing the left side to be cut off.

Please see screenshot:

https://drive.google.com/file/d/1-AwZt_wOh_grHm0nY3f68_TAPEM6znV3/view?usp=drivesdk

**Comment by puppykickr** [comment]
Ok.
I know this isn't really the exact same issue, but it IS another issue with the display.

Testing on my other device, a ZTE 558VL running 7.1.1 shows that the 'clean' button is visible (because this device has dedicated navigation controls) but when analysing and not cleaning the files, they are almost completely covered by the gigantic circle in the center of the screen.

This makes it impossible to scan the files for anything that you do not want deleted.

Please see screenshot:

https://drive.google.com/file/d/18Z_BZJcDXgYgmIVIFHHbb0uXyLYtFtvS/view?usp=drivesdk

**Comment by puppykickr** [comment]
I went ahead and opened my own issue with this, as the OP was difficult to understand.

Hope this is ok.

**Comment by TheRedSpy15** [comment]
Refer to #77
