### ISSUE TITLE
.nomedia files & .thumbnails folders

### ISSUE THREAD

**Issue by ghost** [TheRedSpy15/LTECleanerFOSS#99]
I would like to suggest the deletion of hidden files and folders as they will be recreated every time the respective app is launched, for example:
`DCIM\Camera\.inflight`
`DCIM\Camera\.inflight_lowres`

There are also app-specific ones, for example:
`WhatsApp\.Shared`
`WhatsApp\.StickerThumbs`
`WhatsApp\.Thumbs`
`WhatsApp\.trash`
`WhatsApp\Media\.Statuses`

Folders that contain nothing but hidden files / folders, for example `.nomedia` files / `.thumbnails` folders, should be treated as empty and be deleted recursively.

**Comment by puppykickr** [comment]
If the files are recreated every time the apps are opened, then isn't it kind of a waste of effort to be deleting them?

As far as the .thumbnails folders go, simply delete this folder, then replace it with a file of the exact same name.

This will cause the system to not create another .thumbnail folder, because there is already a file by that same name.

Be sure to save the new item as a file, instead of a folder.

This solved an immense issue for me, as my .thumbnails folder was sometimes multiple GB in size.

Now it is empty all the time.

I whitelisted it on this app so that it would not be deleted.

**Comment by TheRedSpy15** [comment]
> If the files are recreated every time the apps are opened, then isn't it kind of a waste of effort to be deleting them?
> 
> As far as the .thumbnails folders go, simply delete this folder, then replace it with a file of the exact same name.
> 
> This will cause the system to not create another .thumbnail folder, because there is already a file by that same name.
> 
> Be sure to save the new item as a file, instead of a folder.
> 
> This solved an immense issue for me, as my .thumbnails folder was sometimes multiple GB in size.
> 
> Now it is empty all the time.
> 
> I whitelisted it on this app so that it would not be deleted.
